apiVersion: apps/v1
kind: Deployment
metadata:
  name: haadtech-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: haadtechacr2026.azurecr.io/haadtech-frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer # Cực kỳ quan trọng: Mở port ra Internet
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: frontend